on: 
  - workflow_dispatch
name: release
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 , windows-2019, macos-11 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        if: ${{ matrix.os=='ubuntu-20.04' }}
        id: qemu
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: pyproject.toml
      - name: Release wheels
        uses: softprops/action-gh-release@v1
        with:
          files: wheelhouse/*.whl
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          generate_release_notes: true
